title: UHM, what to eat?
description: Food Choice Options in One Place for the UHM Community.
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/orgs/uhm-what-to-eat/repositories
gems:
  - jekyll-mentions
